name: build-test-deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
           dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore "DemoProject.csproj"

      - name: Build
        run: dotnet build "DemoProject.csproj" --configuration Release

      - name: Test
        run: dotnet test "DemoProject.csproj" --verbosity normal
